apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
- ../../base

patchesStrategicMerge:
- replica-count.yaml
- resources.yaml

replicas:
- name: pinky-promise-backend
  count: 3
- name: pinky-promise-frontend
  count: 3

images:
- name: gcr.io/PROJECT_ID/pinky-promise-backend
  newTag: latest
- name: gcr.io/PROJECT_ID/pinky-promise-frontend
  newTag: latest

commonLabels:
  environment: production

