apiVersion: apps/v1
kind: Deployment
metadata:
  name: pinky-promise-backend
spec:
  replicas: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pinky-promise-frontend
spec:
  replicas: 3

