apiVersion: v1
kind: Service
metadata:
  name: pinky-promise-backend
  labels:
    app: pinky-promise-backend
    component: backend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: pinky-promise-backend

