apiVersion: apps/v1
kind: Deployment
metadata:
  name: pinky-promise-backend
  labels:
    app: pinky-promise-backend
    component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pinky-promise-backend
  template:
    metadata:
      labels:
        app: pinky-promise-backend
        component: backend
    spec:
      serviceAccountName: pinky-promise-backend
      containers:
      - name: backend
        image: gcr.io/PROJECT_ID/pinky-promise-backend:latest
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: node-env
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: database-url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: jwt-secret
        - name: JWT_REFRESH_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: jwt-refresh-secret
        - name: RECAPTCHA_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: recaptcha-secret
        - name: PORT
          value: "3000"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}

