apiVersion: apps/v1
kind: Deployment
metadata:
  name: pinky-promise-frontend
  labels:
    app: pinky-promise-frontend
    component: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pinky-promise-frontend
  template:
    metadata:
      labels:
        app: pinky-promise-frontend
        component: frontend
    spec:
      serviceAccountName: pinky-promise-frontend
      containers:
      - name: frontend
        image: gcr.io/PROJECT_ID/pinky-promise-frontend:latest
        ports:
        - containerPort: 80
          name: http
        env:
        - name: REACT_APP_API_URL
          value: "/api"
        - name: REACT_APP_RECAPTCHA_SITE_KEY
          value: "YOUR_RECAPTCHA_SITE_KEY"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 101
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        volumeMounts:
        - name: nginx-cache
          mountPath: /var/cache/nginx
        - name: nginx-pid
          mountPath: /var/run
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: nginx-cache
        emptyDir: {}
      - name: nginx-pid
        emptyDir: {}
      - name: tmp
        emptyDir: {}

