apiVersion: v1
kind: Service
metadata:
  name: pinky-promise-frontend
  labels:
    app: pinky-promise-frontend
    component: frontend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: pinky-promise-frontend

